<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="5" failed="7" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-10T23:48:07 IST" name="NopCommerce Suite" finished-at="2025-09-10T23:53:43 IST" duration-ms="335860">
    <groups>
    </groups>
    <test started-at="2025-09-10T23:48:07 IST" name="E2E Tests" finished-at="2025-09-10T23:50:10 IST" duration-ms="123028">
      <class name="tests.E2ERegisterTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.E2ERegisterTest@43bc63a3]" started-at="2025-09-10T23:48:07 IST" name="setUp" finished-at="2025-09-10T23:48:12 IST" duration-ms="4673" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.E2ERegisterTest.testEndToEndEcommerceFlow() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testEndToEndEcommerceFlow()[pri:0, instance:tests.E2ERegisterTest@43bc63a3]" started-at="2025-09-10T23:48:12 IST" name="testEndToEndEcommerceFlow" finished-at="2025-09-10T23:49:51 IST" duration-ms="99446" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEndToEndEcommerceFlow -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.E2ERegisterTest@43bc63a3]" started-at="2025-09-10T23:49:51 IST" name="logResult" finished-at="2025-09-10T23:49:51 IST" duration-ms="381" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testEndToEndEcommerceFlow status=SUCCESS method=E2ERegisterTest.testEndToEndEcommerceFlow()[pri:0, instance:tests.E2ERegisterTest@43bc63a3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- tests.E2ERegisterTest -->
      <class name="tests.E2ELoginTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.E2ELoginTest@5b12b668]" started-at="2025-09-10T23:49:51 IST" name="setUp" finished-at="2025-09-10T23:49:54 IST" duration-ms="2149" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.E2ELoginTest.testEndToEndEcommerceFlow() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testEndToEndEcommerceFlow()[pri:0, instance:tests.E2ELoginTest@5b12b668]" started-at="2025-09-10T23:49:54 IST" name="testEndToEndEcommerceFlow" finished-at="2025-09-10T23:50:10 IST" duration-ms="16030" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.E2ELoginTest.testEndToEndEcommerceFlow(E2ELoginTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEndToEndEcommerceFlow -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.E2ELoginTest@5b12b668]" started-at="2025-09-10T23:50:10 IST" name="logResult" finished-at="2025-09-10T23:50:10 IST" duration-ms="283" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testEndToEndEcommerceFlow status=FAILURE method=E2ELoginTest.testEndToEndEcommerceFlow()[pri:0, instance:tests.E2ELoginTest@5b12b668] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- tests.E2ELoginTest -->
    </test> <!-- E2E Tests -->
    <test started-at="2025-09-10T23:50:10 IST" name="Functional Tests" finished-at="2025-09-10T23:53:43 IST" duration-ms="212783">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="setupReport()[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:48:06 IST" name="setupReport" finished-at="2025-09-10T23:48:07 IST" duration-ms="457" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupReport -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:50:10 IST" name="setUp" finished-at="2025-09-10T23:50:12 IST" duration-ms="2076" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTest.loginTestBlankCredentials() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestBlankCredentials()[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:50:12 IST" name="loginTestBlankCredentials" finished-at="2025-09-10T23:50:17 IST" duration-ms="4727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestBlankCredentials -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:50:17 IST" name="logResult" finished-at="2025-09-10T23:50:17 IST" duration-ms="253" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTestBlankCredentials status=SUCCESS method=LoginTest.loginTestBlankCredentials()[pri:0, instance:tests.LoginTest@5e5d171f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:50:17 IST" name="setUp" finished-at="2025-09-10T23:50:19 IST" duration-ms="2215" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTest.loginTestInvalidEmail() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestInvalidEmail()[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:50:19 IST" name="loginTestInvalidEmail" finished-at="2025-09-10T23:50:45 IST" duration-ms="26161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestInvalidEmail -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:50:45 IST" name="logResult" finished-at="2025-09-10T23:50:46 IST" duration-ms="298" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTestInvalidEmail status=SUCCESS method=LoginTest.loginTestInvalidEmail()[pri:0, instance:tests.LoginTest@5e5d171f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:50:46 IST" name="setUp" finished-at="2025-09-10T23:50:48 IST" duration-ms="2141" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTest.loginTestInvalidPassword() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestInvalidPassword()[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:50:48 IST" name="loginTestInvalidPassword" finished-at="2025-09-10T23:51:14 IST" duration-ms="25869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestInvalidPassword -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:51:14 IST" name="logResult" finished-at="2025-09-10T23:51:14 IST" duration-ms="237" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTestInvalidPassword status=SUCCESS method=LoginTest.loginTestInvalidPassword()[pri:0, instance:tests.LoginTest@5e5d171f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:51:14 IST" name="setUp" finished-at="2025-09-10T23:51:16 IST" duration-ms="2089" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTest.loginTestValidCredentials() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTestValidCredentials()[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:51:16 IST" name="loginTestValidCredentials" finished-at="2025-09-10T23:51:42 IST" duration-ms="26107" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed: Login was unsuccessful. Please correct the errors and try again.
No customer account found expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed: Login was unsuccessful. Please correct the errors and try again.
No customer account found expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at tests.LoginTest.loginTestValidCredentials(LoginTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestValidCredentials -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:51:42 IST" name="logResult" finished-at="2025-09-10T23:51:42 IST" duration-ms="219" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTestValidCredentials status=FAILURE method=LoginTest.loginTestValidCredentials()[pri:0, instance:tests.LoginTest@5e5d171f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
        <test-method is-config="true" signature="tearDownReport()[pri:0, instance:tests.LoginTest@5e5d171f]" started-at="2025-09-10T23:53:43 IST" name="tearDownReport" finished-at="2025-09-10T23:53:43 IST" duration-ms="775" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownReport -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.ChangePasswordTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.ChangePasswordTest@6c40365c]" started-at="2025-09-10T23:53:04 IST" name="setUp" finished-at="2025-09-10T23:53:06 IST" duration-ms="2151" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.ChangePasswordTest.PasswordTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="PasswordTest()[pri:0, instance:tests.ChangePasswordTest@6c40365c]" started-at="2025-09-10T23:53:06 IST" name="PasswordTest" finished-at="2025-09-10T23:53:22 IST" duration-ms="16204" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.ChangePasswordTest.PasswordTest(ChangePasswordTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PasswordTest -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.ChangePasswordTest@6c40365c]" started-at="2025-09-10T23:53:22 IST" name="logResult" finished-at="2025-09-10T23:53:22 IST" duration-ms="435" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=PasswordTest status=FAILURE method=ChangePasswordTest.PasswordTest()[pri:0, instance:tests.ChangePasswordTest@6c40365c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- tests.ChangePasswordTest -->
      <class name="tests.AddressTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.AddressTest@7d20d0b]" started-at="2025-09-10T23:52:08 IST" name="setUp" finished-at="2025-09-10T23:52:11 IST" duration-ms="2940" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.AddressTest.addNewAddress() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addNewAddress()[pri:0, instance:tests.AddressTest@7d20d0b]" started-at="2025-09-10T23:52:11 IST" name="addNewAddress" finished-at="2025-09-10T23:52:27 IST" duration-ms="16161" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.AddressTest.addNewAddress(AddressTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewAddress -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.AddressTest@7d20d0b]" started-at="2025-09-10T23:52:27 IST" name="logResult" finished-at="2025-09-10T23:52:27 IST" duration-ms="244" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewAddress status=FAILURE method=AddressTest.addNewAddress()[pri:0, instance:tests.AddressTest@7d20d0b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- tests.AddressTest -->
      <class name="tests.CartTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.CartTest@77f1baf5]" started-at="2025-09-10T23:52:27 IST" name="setUp" finished-at="2025-09-10T23:52:29 IST" duration-ms="1986" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.CartTest.cartTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="cartTest()[pri:0, instance:tests.CartTest@77f1baf5]" started-at="2025-09-10T23:52:29 IST" name="cartTest" finished-at="2025-09-10T23:52:45 IST" duration-ms="15962" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.CartTest.cartTest(CartTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cartTest -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.CartTest@77f1baf5]" started-at="2025-09-10T23:52:45 IST" name="logResult" finished-at="2025-09-10T23:52:45 IST" duration-ms="223" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=cartTest status=FAILURE method=CartTest.cartTest()[pri:0, instance:tests.CartTest@77f1baf5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- tests.CartTest -->
      <class name="tests.ProductSearchTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.ProductSearchTest@7bedc48a]" started-at="2025-09-10T23:53:22 IST" name="setUp" finished-at="2025-09-10T23:53:25 IST" duration-ms="2804" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.ProductSearchTest.loginTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTest()[pri:0, instance:tests.ProductSearchTest@7bedc48a]" started-at="2025-09-10T23:53:25 IST" name="loginTest" finished-at="2025-09-10T23:53:42 IST" duration-ms="17126" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.ProductSearchTest.loginTest(ProductSearchTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.ProductSearchTest@7bedc48a]" started-at="2025-09-10T23:53:42 IST" name="logResult" finished-at="2025-09-10T23:53:43 IST" duration-ms="306" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=ProductSearchTest.loginTest()[pri:0, instance:tests.ProductSearchTest@7bedc48a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- tests.ProductSearchTest -->
      <class name="tests.CheckoutTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.CheckoutTest@41a2befb]" started-at="2025-09-10T23:52:45 IST" name="setUp" finished-at="2025-09-10T23:52:47 IST" duration-ms="2209" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.CheckoutTest.cartTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="cartTest()[pri:0, instance:tests.CheckoutTest@41a2befb]" started-at="2025-09-10T23:52:47 IST" name="cartTest" finished-at="2025-09-10T23:53:03 IST" duration-ms="15877" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.CheckoutTest.cartTest(CheckoutTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cartTest -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.CheckoutTest@41a2befb]" started-at="2025-09-10T23:53:03 IST" name="logResult" finished-at="2025-09-10T23:53:04 IST" duration-ms="281" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=cartTest status=FAILURE method=CheckoutTest.cartTest()[pri:0, instance:tests.CheckoutTest@41a2befb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- tests.CheckoutTest -->
      <class name="tests.RegisterTest">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.RegisterTest@24313fcc]" started-at="2025-09-10T23:51:42 IST" name="setUp" finished-at="2025-09-10T23:51:44 IST" duration-ms="2165" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.RegisterTest.registerNewUser() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="registerNewUser()[pri:0, instance:tests.RegisterTest@24313fcc]" started-at="2025-09-10T23:51:44 IST" name="registerNewUser" finished-at="2025-09-10T23:52:07 IST" duration-ms="22994" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewUser -->
        <test-method is-config="true" signature="logResult(org.testng.ITestResult)[pri:0, instance:tests.RegisterTest@24313fcc]" started-at="2025-09-10T23:52:07 IST" name="logResult" finished-at="2025-09-10T23:52:08 IST" duration-ms="273" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=registerNewUser status=SUCCESS method=RegisterTest.registerNewUser()[pri:0, instance:tests.RegisterTest@24313fcc] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logResult -->
      </class> <!-- tests.RegisterTest -->
    </test> <!-- Functional Tests -->
  </suite> <!-- NopCommerce Suite -->
</testng-results>
